yazi-rs/yazi-rs.github.io

- usage/installation.md
```yazi``` has been included in Arch Linux official repository.
> fix: install Yazi from the official repository

- .github/workflows/deploy.yml
- package.json
Uses the same caching method used at https://github.com/yazi-rs/schema/blob/main/.github/workflows/lint.yml, which is the [method recommended by `actions/setup-node`](https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-data).
> ci(deploy): use updated pnpm caching method

- docs/quick-start.md
`mktemp` and `cat` don't exist on windows, so we use the builtin nushell commands
> make nushell script cross platform

- docs/quick-start.md
Use the Nushell mktemp command to avoid [errors](https://github.com/sxyazi/yazi/discussions/501) when attempting to read the TEMP variable.
Improve #18
> docs: fix Nushell shell script

- docs/quick-start.md
In the newest release of nushell, the current `ya` command forces the user to add an argument, or else they'll get the error `Cannot convert nothing to a string`. This simple pull request allows for no arguments by using arguments spreading.
On top of that, I've added the `-p` flag to the `rm` command which forces permanent deleting. `rm` is bundled with nushell and is cross platform, so this should work on all platforms.
Improve #27
> Use nushell arguments spreading

- docs/installation.md
I noticed the URL used for nix home-manager options was not valid, turns out it's just a one character fix!
> docs: fix nix home-manager url

- docs/configuration/keymap.md
- docs/configuration/theme.md
- docs/configuration/yazi.md
- docs/tips.md
https://github.com/sxyazi/yazi/pull/773
Merge it after the Yazi v0.2.4 release.
> docs: add new `run` property

- docs/installation.md
Update documentation for https://github.com/sxyazi/yazi/pull/752
> docs: update Windows installation instruction to use `YAZI_FILE_ONE` for `file(1)` path

- docs/quick-start.md
This PR renames `ya` to `yy`, since it is two consecutive letters, which is easier to type. 
Considering that the file manager will be frequently opened in the terminal, this change will make it more convenient for users.
> docs: rename shell wrapper `ya` to `yy`

- docs/flavors/overview.md
This PR changes `screenshot.png` in the flavor specification to `preview.png`, which is more generic.
Since there are currently no flavors, this is not a breaking change.
> docs: use `preview.png` instead of `screenshot.png` for flavor previews

- docs/plugins/utils.md
Spawn the command returns `(child, err)`
> docs: improve example

- docs/dds.md
The current if condition does not correctly check if the env variable exists and thus triggers the function in every zsh exit (even if it is not a subshell from yazi).
> Small fix to docs on DDS

- docs/tips.md
Drops using `xargs` in favor of shell built-ins.
Issues with `xargs` were discussed in https://github.com/yazi-rs/yazi-rs.github.io/pull/62
> docs: fix Helix file picker shell code

- docs/installation.md
I think the documentation is obsolete here because if I do this an error is raised:
```
$ cargo install --locked --git https://github.com/sxyazi/yazi.git
Updating git repository `https://github.com/sxyazi/yazi.git`
error: multiple packages with binaries found: yazi-cli, yazi-fm. When installing a git repository, cargo will always search the entire repo for any Cargo.toml.
Please specify a package, e.g. `cargo install --git https://github.com/sxyazi/yazi.git yazi-cli`.
```
But this way it is working:
```
$ cargo install --locked --git https://github.com/sxyazi/yazi.git yazi-fm yazi-cli
Updating git repository `https://github.com/sxyazi/yazi.git`
Ignored package `yazi-fm v0.2.5 (https://github.com/sxyazi/yazi.git#07342a29)` is already installed, use --force to override
Updating git …
```
> docs: fix cargo install command

- docs/quick-start.md
`-Path` will leads to error if `$cwd` contains special characters like `[` and `]`, changing to `-LiteralPath` fixes this issue.
> docs: fix function in PowerShell at quick start

- docs/resources.md
I though creating a new category would be better than trying to fit it into the existing ones. It seems more like a tool or utility rather than an integrated plugin. In fact, this is one aspect I'm not satisfied about my solution: it requires some extra steps, including manual file handling. However, I couldn't find a more straightforward or simple solution. Anyway, thanks for the awesome work!
> docs: add `icons-brew.yazi` to resources page

- docs/resources.md
This is plugin which was made by the maintainer of sxyazi/yazi in an issue regarding aliases in zsh(mentioned and acknowledged in the repo). I believe everyone should know about this. 
Thank you.
> docs: add zsh.yazi to shell plugins

- docs/resources.md
This plugin was inspired by [bypass.yazi](https://github.com/Rolv-Apneseth/bypass.yazi) and [fast-enter.yazi](https://github.com/ourongxing/fast-enter.yazi) along with the tips page on the documentation site. It combines all of the features of [bypass.yazi](https://github.com/Rolv-Apneseth/bypass.yazi) and [fast-enter.yazi](https://github.com/ourongxing/fast-enter.yazi) and includes enhancements for some default commands.
> docs: add augment-command.yazi to the resources page

- docs/resources.md
I noticed that the following plugins have been archived:
- https://github.com/DreamMaoMao/keyjump.yazi - @DreamMaoMao
- https://github.com/DreamMaoMao/searchjump.yazi - @DreamMaoMao
- https://github.com/DreamMaoMao/fg.yazi - @DreamMaoMao
- https://github.com/DreamMaoMao/bookmarks-persistence.yazi - @DreamMaoMao
- https://github.com/DreamMaoMao/git-status.yazi - @DreamMaoMao
- https://github.com/DreamMaoMao/mime.yazi - @DreamMaoMao
- https://github.com/DreamMaoMao/yazi.nvim - @DreamMaoMao
which is a strong indication that the maintainers are no longer willing to continue maintaining them, so this PR will remove them from the resources page.
> docs: remove archived plugins

- docs/quick-start.md
Add documentation for multi-tab in Quick Start section.
I didn't even know before that Yazi supports multi-tab. But how to create new tabs? Not `Ctrl+t`, nor `Cmd+t`. I didn't find this keybinding in the [docs](https://yazi-rs.github.io/docs/quick-start). Finally, I found that in this [discussion](https://github.com/sxyazi/yazi/discussions/859), and it turns out that new tab keybinding is in this [keymaps.toml](https://github.com/sxyazi/yazi/blob/main/yazi-config/preset/keymap.toml) file. So I'm considering if it's better to add it to the Quick Start.
> docs: add multi-tab keybindings

- src/css/custom.css
Override the announcement bar height to prevent the following behavior:
Before:
After
The bug seems to only appear on laptop-sized screens since I tested it on a PC and phone and never saw it.
I also tested it in Safari, Firefox, and Chrome-like browsers.
_P.S. Thank you for Yazi. I'm really enjoying it!_
> fix: correct announcement bar height

- docs/plugins/utils.md
I have added ya.clipboard docs in the utils. I am very doubtful about 2 things
1) is it only for Unix or not
2) is "text" word usage appropriate or should it be changed?
I hope everything else is fine.
> docs: add ya.clipboard to utils

- docs/quick-start.md
Using `eval "$(zoxide init --cmd cd zsh)"` in my `.zshrc` overrides the `cd` command. Thus the suggested wrapper does not work anymore.
> docs: specify `cd`-command in bash-zsh shell wrapper

- docs/quick-start.md
This key bind seemed to be missing in the list
> docs: add default keybinding for closing tabs

- docs/configuration/keymap.md
- docs/tips.md
I have weird behavior if I apply previous tips to change header.
Looking into the latest git, then I decided to adapt the way to change header based on the latest git.
Then, looking at the status, I decide to do the same.
> docs: change how to add header & status

- docs/configuration/keymap.md
- docs/configuration/yazi.md
- docs/plugins/utils.md
Referring to issue #73, the Command:std(in|out|err) was already present in the docs.
So i added the `take_std(in|out|err)` under the Child sub, in utils.md
If I have misunderstood any part of it, pls do correct! 
Thanks!
> docs: add take_std(in|out|err) & random sort

- docs/quick-start.md
Hi, 
The wrapper for the fish shell was not working for me because I aliased cat to be bat. It added decorated output to the temp file and resulted in an error when trying to cd to the new path. Adding "command" before cat ensures we call the original cat command.
Thanks for the amazing piece of software!
> docs: updated shell wrapper for fish in quick-start.md

- docs/installation.md
New [nightly tag](https://github.com/sxyazi/yazi/releases/tag/nightly) for pre-build yazi is the game changer.
This PR inform Arch users to install yazi-nightly from AUR.
> docs: add yazi-nightly to install from AUR

- docs/quick-start.md
Makes the wrapper work with `zoxide init fish --cmd cd | source` in fish config.
Same as https://github.com/yazi-rs/yazi-rs.github.io/pull/108, but for `fish`
> docs: specify `cd`-command in fish shell wrapper

- docs/quick-start.md
Many people prefer `cmd.exe` instead of Windows Terminal or PowerShell because `cmd.exe` is faster and it's possible to have all the great features of Windows Terminal / PowerShell with [clink](https://github.com/chrisant996/clink)
> docs: add `yy` command support for cmd.exe (Command Prompt)

- docs/configuration/keymap.md
Add documentation for `--dir` option of `create` command.
> docs: add documentation for `--dir` option of `create` command

- docs/installation.md
Hi, can I add a section to the installation.md documentation explaining how to install Yazi using x-cmd?
- [x-cmd](https://www.x-cmd.com/) is a **toolbox for Posix Shell**, offering a lightweight package manager built using shell and awk.
```sh
x env use yazi fzf 7za jq fd rg zoxide
```
- Furthermore, x-cmd also supports downloading and installing software tools like fzf, 7-Zip(7za), jq, fd, rg, and zoxide.
> Add the method for installing yazi with x-cmd to the documentation.

- docs/cli.md
- docs/configuration/keymap.md
- docs/configuration/yazi.md
- docs/dds.md
- docs/faq.md
- docs/plugins/utils.md
- docs/resources.md
- docs/tips.md
Along with this, some minor additions to custom-shell.yazi description
> docs: adding for some of #70 doc

- docs/configuration/yazi.md
Adds documentation for the `preview.image_delay` and `which.sort_translit` options.
> docs: add documentation for `preview.image_delay` and `which.sort_translit`

- docs/resources.md
This is a plugin for copying file contents from yazi. I tested out "Tips" section, a couple of previously made plugins but nothing worked. So i whipped up this, very simple and straightforward.
I hope it could be added to the list.
Thanks!
> docs: add copy-file-contents.yazi

- docs/resources.md
[first-non-directory](first-non-directory.yazi) is a plugin that allows easy jumping to the first file ignoring directories.
> docs: add a plugin to the jumping section in resources.md

- docs/tips.md
Close #144 
https://github.com/user-attachments/assets/584696cb-89e0-4eaa-8cce-6faa84e350d6
> docs: Improve `File tree picker in Helix with Zellij` tip

- docs/quick-start.md
If users have aliased cat to bat, and have line numbers enabled, the zsh/bash y script will fail
Using \cat to target builtin cat (builtin didn't seem to work, command does but doesn't appear to be cross compatible across bash & zsh)
> docs(quick-start): fix aliased cat error on shell wrapper

- docs/configuration/yazi.md
Specify that `tab_size` refers to the width of a tab character, not a tab in the context of a user interface, which is often used to navigate between different views or sections.
> docs: clarify `tab_size` definition in configuration

- docs/quick-start.md
It's good practice for shell functions to local scope their variables
> docs: do not leak `cwd` variable

- docs/resources.md
Add simple-mtpfs.yazi plugin to 🧩 Functional plugins > File actions. Mounting MTP devices (Android, Camera, etc) in yazi, using simple-mtpfs. 
List devices
> docs: add simple-mtpfs.yazi plugin

- docs/quick-start.md
My computer name has a space in it and the Command Prompt wrapper doesn't work. This fixes the error.
> docs: fix TEMP path with spaces error on shell wrapper

- docs/configuration/keymap.md
- docs/configuration/theme.md
- docs/configuration/yazi.md
What I did: 
1. Compared v0.3.3 sources with existing docs.
2. Added all missing items that I could find.
3. Spell check.
What I did not:
1. Renamed `select` to `pick` - this is upcoming change, I don't want to interfere with releases. But if you wish, I could do that.
Needs attention:
1. `plugin.fetchers`. I never used it, but I did my best to assume stuff based on sources. I'd appreciate if someone could take a glance at what I wrote there.
> docs: introduce missing items

- docs/resources.md
[sips-preview.yazi](https://github.com/andreas-timm/sips-preview.yazi) -
Quick previews of images on macOS. It focuses on PSD (Photoshop) files but also supports other image formats, utilizing the sips command-line tool.
> docs: add `sips-preview.yazi` to preloaders section

- docs/configuration/theme.md
It took me some time today to figure out, why setting the mode style did not work, until I found https://github.com/sxyazi/yazi/pull/1953. So I figured I might as well contribute to the docs of my new favorite file manager.
> docs: update mode styles in theme documentation

- docs/tips.md
Related to; https://github.com/sxyazi/yazi/discussions/281
> docs(tips): default os file manager / picker

- docs/configuration/yazi.md
- docs/plugins/utils.md
I documented the APIs that I have used and know about, but there are many I have no idea how to use, so I didn't document those.
The APIs I didn't document are:
- `redraw_with`
- `app_emit`
- `input_emit`
- `image_info`
- `json_encode`
- `json_decode`
- `spot_table`
- `spot_widgets`
I also reordered the APIs to match the order in the source files, and standardised the style, by adding full stops after every list item and using the colon instead of the dash for the description of the arguments and return values.
> docs: document new APIs

- docs/plugins/types.md
- docs/plugins/utils.md
Also updated `conf` to `pref` as `conf` is deprecated in Yazi v0.4.0.
Follow up to #183.
> docs: reorder APIs to match the source code order

- docs/tips.md
> docs: add smart tab switch tip

- docs/quick-start.md
Makes the following changes to the `y` powershell command:
- Adds UTF8 encoding flag for handling non english characters
- Adds `GetFullPath`, to convert possible `/` to `\`
> fix: make powershell y command work with non-english characters

- docs/quick-start.md
This makes sure that `GetFullPath` gets evaluated before passing its value to `Set-Location`. This prevents `Set-Location` from raising an error "A positional parameter cannot be found that accepts argument 'C:\path\to\dir'".
******
I received this error on both PowerShell and Windows PowerShell ([yes, there's a difference :sweat_smile:](https://learn.microsoft.com/en-us/powershell/scripting/whats-new/differences-from-windows-powershell?view=powershell-7.4)). Additionally I double-checked if there was any difference between PowerShell on Linux and on Windows, just to see if this was somehow OS-specific. This changed resolved the issue for both Windows PowerShell and PowerShell.
Related: https://github.com/yazi-rs/yazi-rs.github.io/pull/191
> docs: fix shell wrapper for PowerShell

- docs/quick-start.md
This PR a [Xonsh](https://xon.sh/) version for the `y` command to the docs. Works smoothly on my machine. WDYT?
> docs: add `y` function for Xonsh

- docs/image-preview.md
Sixel support in Windows Terminal is now stable as of https://github.com/microsoft/terminal/releases/tag/v1.22.10352.0
> docs: update Windows Terminal to stable

- docs/tips.md
Pr introduces a hacky method for using Yazi as a file picker within Helix when running inside a Tmux session. The integration allows users to browse and open files by spawning a new Tmux instance with Yazi and piping the file pick output back to the Helix instance.
> docs: Added tip to use yazi in helix in a tmux session for File Selection

- docs/image-preview.md
This PR adds Bobcat to the list of VTEs that can display images with yazi on Windows.
Requirements:  Bobcat's latest version (v0.9.r242), and the preview version of  `conpty.dll` + `OpenConsole.exe`.
A visual:
> Add Bobcat to the image-preview capable VTEs list (on Windows)

- docs/configuration/theme.md
https://github.com/yazi-rs/yazi-rs.github.io/blob/main/static/img/spot-tbl-explain.jpg
Before:
After:
> fix: incorrect image file extension (png => jpg)

- docs/quick-start.md
The script was showing an error when exiting without changing the directory (Ctrl+Q).
This is now fixed.
> Fix y shell wrapper for cmd on quick-start.md

- docs/tips.md
When I tried this plugin, two last symbols of the text were cut off. I suppose the window frame takes away two symbols, so window width must be set equal to text size + 2.
> Improve confirm-quit plugin in tips.md

- docs/tips.md
Thanks to this helix-editor/helix#12527 now merged helix PR is now possible to open current buffer path instead of project root.
> docs: fix and improve helix tips

- docs/tips.md
Currently, when using the yazi zellij popup for helix from the tips, it shows the command (bash ~/.confg....) as the title of the pane. This isn't quite nice and can be fixed by adding a `-n Yazi` to give the pane the title "Yazi".
> docs: run zellij popup with name

- docs/resources.md
This PR adds `zless-preview.yazi` plugin which is useful for previewing compressed text files using `zless`
> `resources.md` - add `zless-preview.yazi`

- docs/installation.md
I tested this on my Fedora machine. Both `yazi` and `ya` work, and command line auto-completion works for `zsh`. It should also work for `fish` and `bash`, but I didn't test them.
For CentOS Stream, installation works in a container. I don't have a RHEL subscription, but I got yazi to install on Rocky Linux in a container, so I think RHEL works too.
> docs: installation instructions for Fedora and its downstreams

- docs/configuration/keymap.md
To the `keymap.toml` documentation, this PR adds an example of how to run multiple commands using a single keybinding (an array for the `run` value).
> keymap docs - run multiple commands with a single keybinding

- docs/quick-start.md
z / Z were reversed in #2553, but the corresponding documentation doesn't seem to have been updated.
> docs: update default z/Z bindings in quick-start.md

- docs/configuration/yazi.md
- docs/tips.md
changed `<C-e>` to `<C-m>` because it was conflicting with a default keymap
> docs(tips): send selected files with neomutt

- docs/plugins/builtins.md
- docs/plugins/config.md
This PR adds documentation for the built-in plugins fzf and zoxide, including features, usage, and update_db config option.
Closes #71
> docs: add page for built-in plugins fzf and zoxide

- docs/quick-start.md
The shell wrappers currently fail for paths with trailing whitespace.
```bash
mkdir $'foo\n'
y
```
Then navigate to `foo\n` and press <kbd>q</kbd>.
- I replaced `cwd=$(...)` with `read` in bash/zsh/fish.
- I removed the `str:trim-space` in elvish and the `.strip()` in xonsh.
- nushell's `open` appears to preserve whitespace, but then `cd` barfs on it. I don't know enough nushell to fix this.
- Powershell should be fine since it uses `Get-Content`, but I didn't test it.
- I also didn't touch cmd.
> fixed whitespace handling in the shell wrapper

- docs/resources.md
Since I no longer maintain `simple-mtpfs.yazi`, it should be removed. Users can now use `gvfs.yazi` as a replacement.
> docs(resources.md): Add gvfs.yazi, remove predecated/archived simple-mtpfs.yazi

- scripts/typegen.js
These changes are based on the Yazi types file that I maintain together with my augment-command.yazi plugin.
The Color type now shows all the supported named colours like “blue” and “red”.
The Url global is now a function that returns a Url object, as it is not a Url object by itself and is never used that way. This allows the normal usage of `Url(“path/to/file”)` to be properly typed.
The Command global is now either the Command object or a function that returns a Command object. This allows the usage of `Command(“shell_command”)` to be properly typed.
> Improved types

- docs/image-preview.md
Since there are clearly only 3 options needed for `tmux`, I fixed the typo in the readme.
> Fix number of tmux options for image preview

- docs/resources.md
Thanks for yazi it's great!
I wanted the `vcs-files` plugin to also show untracked files as well. I don't know if the vision for that plugin is to show only diff files so I made another plugin that is inclusive.
[keyviz_2025-06-11_20-26-06.webm](https://github.com/user-attachments/assets/af9559c2-f30c-40da-bfb1-97370bdbee03)
first one shows `git status --porcelain` backed
second one shows `git diff --name-only` as your original implementation
> Resources: `git-files.yazi` plugin

- docs/installation.md
Resvg has been moved out of the AUR to the extra repository.
https://gitlab.archlinux.org/archlinux/packaging/packages/yazi/-/merge_requests/12#note_290066
https://archlinux.org/packages/extra/x86_64/resvg/
> Update Arch installation

- docs/installation.md
Added note for overriding 7z dependency in nix, for enabling 7z RAR support.
Without this, RAR files cannot be correctly extracted by yazi in nix.
> Add documentation for 7z RAR support in nix installation

- docs/resources.md
Added clippy.yazi URL to resources.md (clipboard section). The plugin is based on system-clipboard.yazi, but utilizes Clippy. 
The original motivation to use Clippy instead of Clipboard _specifically_ on MacOS is to avoid this particular bug: https://github.com/Slackadays/Clipboard/issues/234
> Add clippy.yazi to resources.md

- docs/configuration/keymap.md
From my testing, "plugin" command for input layer only works in normal mode.  I assume this is a documentation error rather than a bug so I am making the edit here.
> Fix error in "plugin" command for input layer

- docs/tips.md
swaybg can be used independent of sway, ive tested the new keybinding with niri wm
this also removes copying files to your config directory and uses the hovered file as argument
> fix: make swaybg work on more WMs
