usage/configuration/keymap.md
usage/configuration/overview.mdx
usage/configuration/yazi.md
usage/faq.md
usage/quick-start.md

Sorry for all the PRs I can't help myself. Adds a few periods, removes some semicolons, and adds link titles.

feat: improve punctuation and link titles

---

usage/quick-start.md

This PR adds a Fish version of the `ya` function and clarifies the description of the section. Syntax highlighting for Fish is meh but it works.

feat: add fish function for changing working directory on quit

---

docs/installation.md

Add AOSC OS Installation to docs

docs: add AOSC OS Installation

---

docs/configuration/keymap.md

> There are x "sections" of the `keymap.toml` file: manager, tasks... TOML stuff... `keymap = [ { ... } ]`.

refactor: make each little thing a linkable heading

---

docs/configuration/theme.md

https://github.com/sxyazi/yazi/pull/628

docs: add char device in filetype for theme

---

docs/configuration/yazi.md

Adds documentation for https://github.com/sxyazi/yazi/pull/679

docs: add `scrolloff` option to `[manager]` in `yazi.toml`

---

docs/configuration/keymap.md

Documentation for https://github.com/sxyazi/yazi/pull/687

docs: add a new option `--hovered` to the `open` command

---

docs/resources.md

Some simple instructions to display an indicator in a shell's prompt.

docs: add yazi-prompt.sh to resources

---

docs/configuration/keymap.md

docs: improve the `select_all` command doc

---

docs/installation.md

Fix: https://github.com/yazi-rs/yazi-rs.github.io/issues/48

docs: add installation guide for nix flakes

---

docs/tips.md

docs: skip files when navigating in the parent directory

---

docs/plugins/types.md

Merge it once Yazi is v0.2.5 released

docs: add is_exec and is_sticky to Cha

---

docs/tips.md
package.json

Requested from https://github.com/zellij-org/zellij/issues/3018#issuecomment-2094300680

Add tip to use Yazi as a Helix file picker with Zellij

---

docs/tips.md

changes:
1. change 28 to 27 in line 1
2. add extra space in the beginning ofr line 2

docs: fix full border patch

---

docs/resources.md

https://github.com/ourongxing/fast-enter.yazi

docs: add fast-enter.yazi to resources page

---

docs/configuration/keymap.md

As requested by https://github.com/sxyazi/yazi/pull/1227#issuecomment-2195894477

feat: add the `--hovered` option to the `remove` and `rename` commands

---

docs/resources.md

This is fish.yazi, very much inspired from zsh.yazi. This will be useful for all the fish lovers.
Thank you.

docs: add custom-shell.yazi in shell plugins

---

docs/resources.md

add git-status.yazi to resources page

docs: add git-status.yazi to resources page

---

docs/resources.md

https://github.com/imsi32/yatline.yazi

 docs: add `yatline.yazi` to resources page 

---

docs/plugins/utils.md
docs/resources.md

Adding Jupyter notebook preview plugin in docs.

docs: add nbpreview.yazi

---

docs/resources.md

Added archivemounting for archives for Linux, as a plugin in Yazi

docs: added archivemount.yazi

---

docs/configuration/yazi.md

docs: remove mention of bug on sort_by: creation

---

docs/image-preview.md
docs/installation.md

Merge it once Yazi v0.3 released

docs: prepare for v0.3.0 release

---

docs/dds.md

Add `Change Yazi's CWD to PWD on subshell exit` script for fish shell

docs: add `Change Yazi's CWD to PWD on subshell exit` script for fish shell

---

docs/resources.md

add lazygit.yazi plugin

---

docs/resources.md

Not sure if "Jumping" is the right category, but it makes sense I think.

docs: add zfs.yazi for jumping

---

docs/installation.md

The right package ID in winget is sxyazi.yazi.

docs: fix WinGet package name

---

docs/resources.md

Added dual-pane.yazi and togle-view.yazi plugins

docs: update resources.md

---

docs/resources.md

Add restore.yazi plugin to 🧩 Functional plugins > File actions

Add restore.yazi plugin

---

docs/configuration/theme.md

Include an example combining `hidden` and `dir` conds
Based off request here: https://github.com/sxyazi/yazi/pull/1843#issuecomment-2439872061

docs: update `theme.md` with `conds` examples

---

docs/configuration/theme.md

Add marker_marked to style doc.

---

docs/tips.md

Shell command keybinding to send selected files using Thunderbird.
It took me way too long, so hopefully this may save someone some time.
Only tested on Linux.

docs: email selected files using Thunderbird

---

docs/resources.md

Now with BTRFS support! :rocket:

docs: update zfs.yazi to time-travel.yazi

---

docs/resources.md

Add bunny.yazi bookmarks plugin that I just finished working on.

Update resources.md, add bunny.yazi plugin

---

docs/resources.md

Suggestion for the new plugin which may be useful to others.

Add a small plugin to copy file path relative to git root

---

docs/cli.md
docs/dds.md

Add examples showing how to add and remove multiple plugins simultaneously using ya pack -a and ya pack -d commands

docs: update `ya pack` command examples for multiple packages

---

docs/installation.md

docs: add flatpak installation instructions

---

docs/resources.md

- Add simple-tag.yazi and pref-by-location.yazi plugins to resources.md.
- Update mediainfo.yazi description in resources.md.

docs: add simple-tag.yazi and pref-by-location.yazi to resources.md

---

docs/resources.md

I just released v1.0.0 of this plugin which contains significant changes so I wanted to update the description here.

docs: update description of bunny.yazi plugin

---

docs/resources.md

- Created a new “Data files” classification in pre-loaders.
- Moved miller.yazi into data files and removed CSV classification.
- Added duckdb.yazi to previewers.

Added duckdb.yazi to resources.md

---

docs/quick-start.md

If yazi is used in the ConstraintLanguageMode the y function needs to use Powershell-native way of doing things. The new version would work both in regular and in the constraint modes.

Powershell integration that is ConstraintLanguageMode compatible

---

docs/resources.md

adds a plugin that can preview comicbook archive files with scrolling.

docs: add comicthumb.yazi to resources.md

---

docs/resources.md

Adds a plugin for quickly navigating to the root of the current git directory

docs: add cd-git-root.yazi to resources.md

---

docs/resources.md

Adds a plugin for managing your Trash on Linux. 
- Browse, restore, or permanently delete trashed files. 
- Includes age-based cleanup and bulk actions.

docs: add recycle-bin.yazi to resources.md

---

docs/configuration/yazi.md

Documentation was not clear about disabling the mouse input globally.

Update yazi.md with mouse input disable instructions

---

docs/resources.md

[mux.yazi](https://github.com/peterfication/mux.yazi) - Plugin multiplexer. Define and cycle through previewers for the same file.

Add mux.yazi plugin to resources
